Repository ably/ably-ui, pull requests merged in 2025-02, with the labels that each got.

#625 [WEB-4205] - Flyout Component for Meganav
  package.json
  src/core/Flyout.tsx
  src/core/Flyout/Flyout.stories.tsx
  src/core/Flyout/__snapshots__/Flyout.stories.tsx.snap
  src/core/Header.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement, review

#646 Change the Table Supported Icon to solid
  src/core/Table/__snapshots__/Table.stories.tsx.snap
  src/core/Table/data.tsx
Labels: enhancement

#649 [WEB-4082] Divide header into three equal parts
  package.json
  src/core/Header.tsx
  src/core/Header/Header.stories.tsx
  src/core/Header/HeaderLinks.tsx
Labels: review

#664 chore: add environment to github pages workflow
  .github/workflows/release.yml
  .github/workflows/review.yml
Labels: review
